eclipse-tractusx/digital-product-pass

.github/workflows/release-helm-charts.yml
- Added dispatch property in workflow.
=> Updated release chart workflow, added dispatch

charts/consumer-backend/Chart.yaml, charts/consumer-ui/Chart.yaml
- Cached versions need to be updated
- Updating version of Chart to 0.2.0
=> Updated Chart Versions

.github/workflows/publish-consumer-backend-docker-images.yml, .github/workflows/publish-consumer-ui-docker-images.yml, charts/consumer-backend/Chart.yaml, charts/consumer-backend/values.yaml, charts/consumer-ui/Chart.yaml, charts/consumer-ui/values.yaml
- Updated Image deployment to tagged version release
- Updated git workflow to release when a tag is created
=> Image deployment hotfix, build image to tagged version

.nginx/nginx.conf, CHANGELOG.md, DEPENDENCIES_BACKEND, DEPENDENCIES_FRONTEND, Dockerfile, charts/digital-product-pass/Chart.yaml, charts/digital-product-pass/values-beta.yaml, charts/digital-product-pass/values-dev.yaml, charts/digital-product-pass/values-int.yaml, charts/digital-product-pass/values.yaml, docs/RELEASE_USER.md, package-lock.json, package.json
The frontend application deployment contains a bug that affects the stability of the DPP app in a critical way.
We want to fix the bug detected in the following issue: #30 
- Updated the NGINX configuration
- Updated ingress templates in product helm charts
- Added the base image recommended by the TRGs: `nginxinc/nginx-unprivileged:stable-alpine` in the frontend image generation.
- Updated version from vite to `v4.1.5` to fix critical vulnerability raised by the dependapot: https://github.com/eclipse-tractusx/digital-product-pass/security/dependabot/2
=> Release/v0.8.1-frontend-fixes: Resource loading bug

CHANGELOG.md
To change the release status in the changelog
Get the status changed
- Changelog status
=> Release/v0.8.1-frontend-fixes: Changed release status in changelog

.github/workflows/publish-dpp-backend-docker-image.yml, .github/workflows/publish-dpp-frontend-docker-image.yml
**This PR is created for testing purposes to test publishing container images onto the docker.io.**
Following the PR https://github.com/eclipse-tractusx/digital-product-pass/pull/63. To refactor the following docker workflows and place container images onto the Docker Hub registry:
publish-dpp-backend-docker-image.yaml
publish-dpp-backend-docker-image.yaml
To grant public access to dpp container images on Docker Hub.
A new container registry where dpp container images are publicly accessible.
https://github.com/eclipse-tractusx/digital-product-pass/pull/63
=> Feature/docker-images: remove feature branch from branches list in docker workflows

CHANGELOG.md, DEPENDENCIES_BACKEND, charts/digital-product-pass/Chart.yaml, charts/digital-product-pass/values-beta.yaml, charts/digital-product-pass/values-dev.yaml, charts/digital-product-pass/values-int.yaml, consumer-backend/productpass/pom.xml, package-lock.json, package.json, src/services/service.const.js
There is a bug related with the frontend reported here: https://github.com/eclipse-tractusx/digital-product-pass/issues/118
We want to fix the bug in the release  and fix the necesary security bugs
Prepare release `v1.0.0-rc2`
- Updated helm charts to fix the frontend configuration bug
- Fixed Spring Boot Security Vulnerability Upgrade from `3.1.0` to `3.1.2`
=> Release/v1.0.0-rc1-helm: Fixed bug related with frontend configuration + security vulnerabilities

README.md
To fix the version of the application in the readme reference.
Update the version in the readme 
- Updated version in main readme
=> Hotfix/v1.0.0-rc2: Updated Readme

.github/workflows/sonar-scan.yaml, CHANGELOG.md, README.md, charts/digital-product-pass/Chart.yaml, charts/digital-product-pass/values.yaml, docs/RELEASE_USER.md, package-lock.json, package.json
After the release candidate `v1.0.0-rc2` passed all the necesary security tests the version v1.0.0 needs to be prepared
Add the final details to pass the release `v1.0.0-rc2` to `v1.0.0`
- Added patch to Sonar Cloud Scan for detecting the secrets
- Prepared v1.0.0 release
- Fixed linting issues
- Upgraded the charts
=> Release/v1.0.0: Prepared release v1.0.0 + Release Documentation

CHANGELOG.md, charts/digital-product-pass/Chart.yaml, charts/digital-product-pass/README.md, charts/digital-product-pass/values.yaml, consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/http/controllers/AppController.java, package-lock.json, package.json
Our `values.yaml` charts needs to be with security checks disabled.
Disable the security checks from the workflow.
- Disabled security checks in charts values
- Updated Helm Docs
=> Hotfix/v1.0.0 rc3: Added security checks by default in chart

.github/workflows/helm-test.yaml, charts/digital-product-pass/Chart.yaml, package-lock.json, package.json
There was the need of preparing the release because of the release candidate.
Prepare the release v1.0.0 and fix helm test: #122 
- Updated the release v1.0.0 docs
- Fixed helm test workflow and removed upgrade section
=> Release v1.0.0: Prepared release 1.0.0 from release/1.0.0-rc3

CHANGELOG.md, charts/digital-product-pass/Chart.yaml, package.json
We want to release the Release Candidate 4 as the new stable release v1.0.0
Have a stable release version `v1.0.0`
- Changed charts to release v1.0.0
=> Release/v1.0.0- Prepared release v1.0.0 from release v1.0.0-rc4

src/services/service.const.js
Solve problem from wrong path in frontend
Update the path
- Fixed auth path in the const file from the frontend configuration
=> chore: fixed auth path in const from frontend

.github/workflows/publish-swagger-hub.yaml
Update the workflow from swagger
Update the workflow from swagger
- Fixed problem with workflow path
=> chore: updated workflow to new packege path

.github/workflows/publish-swagger-hub.yaml
Update the workflow from swagger
Update the workflow from swagger
- Fixed problem with workflow path
=> fix: increased to 20 seconds swagger sleep

docs/RELEASE_USER.md
Added the release user that was not included in the last PRs from the release v2.0.0
Added release user to the main
The user release was outdated
=> Hotfix/Release User: Updated the user release file

dpp-backend/digitalproductpass/Dockerfile
The backend configuration of the docker file is wrong
Update the docker file to be matching
Updated the docker file
=> chore: updated docker file backend

CHANGELOG.md, charts/digital-product-pass/Chart.yaml, charts/digital-product-pass/README.md, charts/digital-product-pass/templates/deployment-backend.yaml, charts/digital-product-pass/templates/deployment-frontend.yaml, charts/digital-product-pass/values.yaml, deployment/infrastructure/edc-provider/data-service/templates/deployment.yaml, deployment/infrastructure/edc-provider/data-service/values.yaml, docs/RELEASE_USER.md, dpp-backend/charts/digital-product-pass-backend/Chart.yaml, dpp-backend/charts/digital-product-pass-backend/README.md, dpp-backend/digitalproductpass/pom.xml, dpp-backend/digitalproductpass/readme.md, dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/models/catenax/Discovery.java, package-lock.json, package.json
Added some checks to the dpp helm template:
- added `readOnlyRootFilesystem` to the container security context
- Updated helm template to provide security context values from the helm vaules file
- added `readOnlyRootFilesystem` to the container security context
- Updated helm template to provide security context values from helm vaules file
=> [ 8° ] - Release/v2.1.0 dpp helm template: Refactor dpp helm template

src/assets/styles/components/general/contractModal.scss, src/views/PassportView.vue
<< Quick description why the PR is being opened >>
<< Quick description of the objective of the PR >>
<< Content of the version change log functionalities OR functionalities >>
<< If there is a ticket include it here >>
| Tickets |
| :---:   |
| [cmp-xxx](www.link.com) |
| [cmp-xxx](www.link.com)  |
=> Bugfix/cmp 1119/policy style fix

src/assets/styles/components/general/contractModal.scss, src/utils/edcUtil.js, src/utils/jsonUtil.js, src/views/PassportView.vue, src/views/SearchView.vue
We need to update and show the policies with more details in our policy dialog
Be able to visualize the policies in a more intuitive way
- Policy visualization card with detailed information about prohibitions, permissions and obligations
With styles it looks like this:
https://github.com/eclipse-tractusx/sig-release/issues/511
=> [ 1° ] - Hotfix/odrl-information: Added policy description to the policy selection popup

src/assets/styles/components/general/contractModal.scss, src/components/general/QrcodeStrem.vue, src/utils/edcUtil.js, src/utils/jsonUtil.js, src/views/PassportView.vue, src/views/SearchView.vue
There are some differences of style between Catena-X and our app 
Align with Catena-X style guide and fix qr code issue
- Align UI style
- Policy modal responsiveness 
- A more descriptive policy choice
- QR code reader bug fix
=> [ 2° ] - Release/v2.1.2 policy styles

README.md, charts/digital-product-pass/Chart.yaml, charts/digital-product-pass/README.md, charts/digital-product-pass/templates/deployment-backend.yaml, charts/digital-product-pass/values.yaml
This PR contains the following changes:
- Added the Prerequisites and TL;DR in the chart readme
- Externalized the persistent volume configuration (volumeMounts and volumes) from in the helm values
- Updated the helm chart version to v2.1.4
To meet the TRG 5 requirements
Updated helm charts to v2.1.4
Closes #234
=> chore: fix trg-5 requirements from dpp helm chart

DEPENDENCIES_FRONTEND, package-lock.json, package.json
There was the need of adding a new chart library for the frontend
Add frontend library `vue-chartjs` into the dependencies and run the IP checks
- Added `vue-chartjs` library to the frontend dependencies
=> feat(library): added vue-chartjs library to frontend packege and run ip checks

dpp-tutorial/resources/test-data/serialPartItems.json
Update the test data from the dpp tutorial serial part items
=> chore: added more test data to the serial part items

README.md, dpp-verification/README.md, dpp-verification/charts/simple-wallet/Chart.yaml, dpp-verification/charts/simple-wallet/LICENSE, dpp-verification/charts/simple-wallet/templates/_helpers.tpl, dpp-verification/charts/simple-wallet/templates/configmap.yaml, dpp-verification/charts/simple-wallet/templates/deployment.yaml, dpp-verification/charts/simple-wallet/templates/ingress.yaml, dpp-verification/charts/simple-wallet/templates/pvc-data.yaml, dpp-verification/charts/simple-wallet/templates/service.yaml, dpp-verification/charts/simple-wallet/templates/tests/test-connection.yaml, dpp-verification/charts/simple-wallet/values.yaml, dpp-verification/semantics/io.catenax.dpp_verification.cdc/1.0.0/CertifiedDataCredential.ttl, dpp-verification/simple-wallet/Dockerfile, dpp-verification/simple-wallet/README.md, dpp-verification/simple-wallet/config/configuration.yml, dpp-verification/simple-wallet/config/logging.yml, dpp-verification/simple-wallet/init.py, dpp-verification/simple-wallet/passport/sammSchemaParser.py, dpp-verification/simple-wallet/utilities/cryptool.py, dpp-verification/simple-wallet/utilities/httpUtils.py, dpp-verification/simple-wallet/utilities/operators.py
- Updated  copyright headers in dpp verification
=> chore(license-headers): update copyright headers in dpp verification

DEPENDENCIES_BACKEND, dpp-backend/digitalproductpass/pom.xml
- Updated spring boot dependencies, reported by dependabot. 
- Updated spring boot dependencies, reported by dependabot. 
https://github.com/eclipse-tractusx/digital-product-pass/pull/347
https://github.com/eclipse-tractusx/digital-product-pass/pull/339
https://github.com/eclipse-tractusx/digital-product-pass/pull/329
https://github.com/eclipse-tractusx/digital-product-pass/pull/219
=> chore(deps): updated spring-boot dependencies

DEPENDENCIES_BACKEND, dpp-backend/digitalproductpass/pom.xml
Updated springboot starter parent version to `3.3.1`
Fixed tomcat vulnerability: https://github.com/eclipse-tractusx/digital-product-pass/security/code-scanning/1634
IP checks already executed, no IP issues found
There was a HIGH vulnerability in the tomcat springboot. Updated springboot parent version resolved this issue. 
- Updated Springboot version to fix HIGH vulnerability
=> chore(DEPEMDENCIES): update Springboot version to fix HIGH vulnerability 

deployment/infrastructure/data-consumer/edc-consumer/Chart.yaml, deployment/infrastructure/data-consumer/edc-consumer/values-int.yaml, deployment/infrastructure/data-consumer/edc-consumer/values.yaml, deployment/infrastructure/data-provider/edc-provider/Chart.yaml, deployment/infrastructure/data-provider/edc-provider/values-int.yaml, deployment/infrastructure/data-provider/edc-provider/values.yaml
- Updated the edcs Chart file to the compliant version `v0.7.3`
- Adapted values file accordingly
- Removed vault related configuration from the default values file
The edc must be updated and compliant with the release `R24.08`
- Updated edcs version to `v0.7.3`
=> Chore/edcs v0.7.3: Updated EDCs to v0.7.3

.github/workflows/trufflehog.yml, DEPENDENCIES_BACKEND
The main workflow is failing becase we have no IP CHECK updated
Also updated trufflehog workflow
Update IP check dependencies for backend.
- Dependency file for backend, updated
- Fixed truffle hog
=> feat: executed ip checks for backend

dpp-tutorial/resources/digital-twins/car-dt-template.json, dpp-tutorial/resources/digital-twins/example-dt.json
- Update asset id in dt-example payload
=> chore: update asset id in  dt-example payload
