CHANGELOG.md
DEPENDENCIES_BACKEND
charts/consumer-backend/Chart.yaml
charts/consumer-ui/Chart.yaml
consumer-backend/productpass/pom.xml
docs/RELEASE_USER.md
package-lock.json
package.json

- Upgraded version from Snake Yaml from v1.33 to v2.0

Release/v0.4.5: Snake Yaml Library Version Updated to 2.0

---

CHANGELOG.md
DEPENDENCIES_BACKEND
charts/consumer-backend/Chart.yaml
charts/consumer-ui/Chart.yaml
consumer-backend/productpass/pom.xml
consumer-backend/productpass/readme.md
docs/RELEASE_USER.md
package-lock.json
package.json

In the day 11.04.2023 two vulnerabilities were detected by our team using Veracode. This vulnerabilities affect the released version `v0.5.1` from our application.
We want to fix the vulnerability in the backend so that the application becomes more safe
- Updated Spring Boot Version from `v3.0.2` to `v3.0.5` fixing the following vulnerable libraries:
- Spring Expression *v6.0.4* -> `v6.0.7`
- JSON Smart *v2.4.8* -> `v2.4.10`

Release/v0.5.2: Fixed libraries vulnerabilities

---

charts/consumer-backend/.helmignore
deployment/helm/edc-provider/data-service/.helmignore
deployment/helm/edc-provider/data-service/README.md
docs/IaC.md
docs/SECRETS_MANAGEMENT.md
docs/admin guide/Admin_Guide.md
docs/business statement/Business Statement.md
docs/cypress/CYPRESS.md
docs/user manual/User Manual Product Viewer App.md
src/assets/styles/components/general/notFound.scss
src/assets/styles/components/landing/searchView.scss
src/assets/styles/components/passport/cards.scss
src/assets/styles/components/passport/elementChart.scss
src/assets/styles/components/passport/field.scss
src/assets/styles/components/passport/passportPage.scss
src/components/general/ErrorComponent.vue
src/components/passport/BarChart.vue
src/components/passport/Cards.vue
src/utils/threadUtil.js

Includes #16 (v0.6.0.0) + #17 (v0.6.0.1) + #18 (v0.6.0.2) + #19 (v0.6.0.3) + #20 (v0.6.0.4) + #21 (v0.6.0.5) + #24 (v0.6.0.6) 
= `v0.6.0`
In the PR #16 there was detected that some license headers were missing or were incorrect.
This PR adds the fixes for that #16 PR, adding the missing license headers.
- Updated pull request (PR) template description
- Upgrade battery pass test data for Passport Semantic version `v3.0.1`
- Adjusted footer and search components in consumer frontend
- Updated documentation for the digital product pass (Arc42 + Admin Guide)
- Removed history table from Dashboard page 
- Implemented new User Interface (UI) design for battery passport page
- Added digital product passport (DPP) logo and favicon icon for DPP frontend component 
- 404 and Error message in …

Sub-Release 6: Release/v0.6.0: Updated and Added license headers

---

.github/workflows/publish-dpp-frontend-docker-image.yml

**This PR is created for testing purposes to test publishing container images onto the docker.io.**
Following the PR https://github.com/eclipse-tractusx/digital-product-pass/pull/66. To fix the image name in publish-dpp-frontend-docker-image.yaml.
To grant public access to dpp container images on Docker Hub.
A new container registry where dpp container images are publicly accessible.
https://github.com/eclipse-tractusx/digital-product-pass/pull/66

fix image name in docker frontend workflow

---

CHANGELOG.md
src/components/general/Footer.vue
src/services/BackendService.js

When the passport was requested from the frontend side sometimes the passport was not being retrieved since the passport was received but the status was not completed.
We want to fix the bug for including it in the release v1.0.0 updating the pre-release
- Fixed bug related to backend get status, where it looped over the status received.

Hotfix/v1.0.0-alpha: fixed infinite loop related to get status bug

---

consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/http/controllers/api/ApiController.java
src/services/BackendService.js

This PR includes a little change in the charts so that a version gets created.
When the passport was requested from the frontend side sometimes the passport was not being retrieved since the passport was received but the status was not completed.
We want to fix the bug for including it in the release v1.0.0 updating the pre-release
- Fixed bug related to backend get status, where it looped over the status received.

Hotfix/v1.0.0-alpha: fixed infinite loop related to get status bug #76

---

charts/digital-product-pass/templates/tests/test-dpp-connection.yaml

There was missing one licence header which was not detected in the previous PR of this branch.

chore: added missing license header to test file

---

charts/digital-product-pass/LICENSE

There is a requirement in the TRGs that states that the helm charts released need to include the License.
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02/
A issue was raised to fix this point: https://github.com/eclipse-tractusx/digital-product-pass/issues/110
We want to include the Apache license and comply to the TRGs
- Added the license in the helm charts directory

hotfix/v1.0.0-rc1-license: Added license in helm charts directory

---

.github/workflows/trivy.yml
docs/GETTING-STARTED.md
docs/IaC.md
docs/RELEASE.md
docs/RELEASE_USER.md
docs/SECRETS_MANAGEMENT.md
docs/admin guide/Admin_Guide.md
docs/arc42/Arc42.md
docs/business statement/Business Statement.md
docs/cypress/CYPRESS.md
docs/readme.md
docs/user manual/User Manual Product Viewer App.md

This PR contains the following hotfix changes:
- Added notice section to readme files in docs folder
- Fix trivy workflow to support scanning of latest docker images 
- Added notice section to docs in order to fulfill the [TRG 7.07](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07/#documentation) requirement
- Fix trivy workflow to support latest container images for QGs approval.
This PR relates to the following GitHub issues:
- https://github.com/eclipse-tractusx/digital-product-pass/issues/108#issuecomment-1683608930
- https://github.com/eclipse-tractusx/digital-product-pass/issues/60
- Added a NOTICE section to readme files in docs
- Fix issues in trivy workflow file

Hotfix/v1.0.0 docs trivy: add Notice in docs and fix trivy workflow

---

.github/actions/setup-java/action.yaml
.github/workflows/publish-swagger-hub.yaml

A workflow is prepared in order to host backend API specs to the central swaggerhub
Link: https://app.swaggerhub.com/apis/eclipse-tractusx-bot/digital-product-pass/1.3.1
To include the API specs to the EcoPass Kit for a reference implementation https://eclipse-tractusx.github.io/docs-kits/kits/Eco_Pass_KIT/page-software-development-view/#api-specification
- Added SwaggerHub workflow to host backend API Specs for a reference implementation
https://github.com/eclipse-tractusx/eco-pass-kit/issues/20

[ 11º ] - Feature/swaggerhub workflow: Prepared workflow to host backend API specs to the central swaggerhub

---

AUTHORS.md
CHANGELOG.md
DEPENDENCIES_BACKEND
DEPENDENCIES_FRONTEND
README.md
charts/digital-product-pass/Chart.yaml
charts/digital-product-pass/README.md
charts/digital-product-pass/templates/configmap-backend.yaml
charts/digital-product-pass/values.yaml
docs/RELEASE_USER.md
dpp-backend/charts/digital-product-pass-backend/Chart.yaml
dpp-backend/charts/digital-product-pass-backend/README.md
dpp-backend/charts/digital-product-pass-backend/templates/configmap.yaml
dpp-backend/charts/digital-product-pass-backend/values.yaml
dpp-backend/digitalproductpass/pom.xml
dpp-backend/digitalproductpass/readme.md
dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/config/DtrConfig.java
dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/http/controllers/api/ContractController.java
dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/http/controllers/api/IrsController.java
dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/listeners/AppListener.java
dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/managers/DtrSearchManager.java
dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/models/catenax/Dtr.java
dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/services/CatenaXService.java
dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/services/DataTransferService.java
dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/services/IrsService.java
dpp-backend/digitalproductpass/src/main/java/utils/JsonUtil.java
dpp-backend/digitalproductpass/src/main/resources/application.yml
package-lock.json
package.json

There are a list of several security issues with the applicaition and also some bugs that need to be fixed for the version v2.0.0.
Create the release v2.0.1 with all the security issues fixed and the bugs fixes detected in the post testing phase.
- Added function to check for duplicated DTRs in the temporaryStorage
- Added check for skipping the check of all BPNs when the DTRs are not available for security and optimization
- Added `vue-i18n v9.2.2` library that will be used in the release `v2.1.0` with the translations
- Added check to fix bug related to invalid BPN endpoints in cache
- Updated header license of modified files to match the new year 2024
- Updated Axios from version `v0.8.1` -> `v1.6.0`
- Updated Spring Boot from version `v3.1.5` -> `v3.2.1`
- Logback from Log4j got …

Hotfix/v2.0.1 security patch: Fixed security Issues

---

CODE_OF_CONDUCT.md

- This PR updates the code of conduct file to the latest version (January 1, 2023) of the EF.
- removed the Catena-X copyright header as this file is property of the EF.
updates https://github.com/eclipse-tractusx/digital-product-pass/issues/180

chore: update code of conduct to latest version

---

.github/workflows/publish-swagger-hub.yaml
CHANGELOG.md

The swagger workflow had a bug that it didn't redirect to the latest release tag e.g., `2.2.0` by default once a new released is published and swagger is accessible from the link https://app.swaggerhub.com/apis/eclipse-tractusx-bot/digital-product-pass
This PR contains the following changes:
- Resolved the release version tagging issue.
- Refactored the workflow
To trigger the workflow and publish OpenAPI specs through central swaggerhub https://app.swaggerhub.com/apis/eclipse-tractusx-bot/digital-product-pass once a new release is published. The API specs must access the new published version of  release tag by default.
- Refactored the swagger worflow
- Fixed tagging issue in the swagger worflow 
#279

chore(swagger-bugfix): refactor workflow to resolve release version tag issue 

---

CHANGELOG.md
README.md
charts/digital-product-pass/Chart.yaml
charts/digital-product-pass/README.md
charts/digital-product-pass/values.yaml
docs/RELEASE_USER.md
dpp-backend/charts/digital-product-pass-backend/Chart.yaml
dpp-backend/charts/digital-product-pass-backend/README.md
dpp-backend/digitalproductpass/src/main/resources/application.yml
dpp-frontend/package-lock.json
dpp-frontend/package.json
dpp-verification/README.md

To publish the digital product pass application used in the E2E tests. 
Publish the application and update the charts.
- Updated charts
- Set dpp verification documentation to released
- Updated default constraint from framework agreement to CircularEconomy from circulareconomy

chore(release): updated release version to 3.0.0 from 3.0.0-rc1

---

charts/digital-product-pass/templates/deployment-backend.yaml
charts/digital-product-pass/templates/deployment-frontend.yaml
charts/digital-product-pass/templates/secret-backend.yaml
charts/digital-product-pass/values-int.yaml
charts/digital-product-pass/values.yaml
dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/managers/TreeManager.java
dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/models/irs/IrsShell.java
dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/models/irs/JobResponse.java
dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/services/IrsService.java
dpp-backend/digitalproductpass/src/main/java/utils/HttpUtil.java
dpp-backend/digitalproductpass/src/main/resources/application.yml
dpp-backend/digitalproductpass/src/test/java/services/IrsServiceTest.java
dpp-backend/digitalproductpass/src/test/resources/application-test.yml
dpp-backend/digitalproductpass/src/test/resources/dpp/irs/TestJobResponse.json

- Added apiKey to the api request headers in backend and in helm charts
- Added IrsShell class to parse the IRS JobResponse payload
- Update `DigitalTwin` references with `IrsShell` to TreeManager class to retrieve child components
- Update unit tests to IrsService
To make IRS drill down to work with the new EDC `0.7.0` 
- Added apiKey to the api request headers in backend and in helm charts
- Added IrsShell class to parse the IRS JobResponse payload
- Update `DigitalTwin` references with `IrsShell` to TreeManager class to retrieve child components
- Update unit tests to IrsService
PR #327 
Issue #266

Feature/irs: Make IRS compatible to the dpp-backend

---

CHANGELOG.md
docs/RELEASE_USER.md

Updated changelog.md , RELEASE_USER.md and dpp helm chart versions `v3.1.0`.
- Changelog.md
- RELEASE_USER.md
- DPP Helm Chart version
Closes #274

release/v3.1.0/chore(changelog): updated CHANGELOG.md and helm chart version

---

dpp-verification/simple-wallet/Dockerfile

There is a vulnerability in the generation of the images that needed to be fixed.
Closes https://github.com/eclipse-tractusx/digital-product-pass/security/code-scanning/1617

fix(vulnerability): wallet no cache vulnerability fixed

---

deployment/infrastructure/data-provider/registry/Chart.yaml

Update digital twin registry version
Helm Chart version `v0.5.2`
AppVersion: `0.5.0`
- Updated digital twin registry version

chore(dtr): update dtr chart version to v0.5.0

---

docs/data-sovereignty/PolicyConfigGuide.md
dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/core/models/negotiation/policy/Action.java
dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/core/models/negotiation/policy/Constraint.java
dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/core/models/negotiation/policy/LogicalConstraint.java
dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/core/models/negotiation/request/TransferRequest.java
dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/core/services/DataTransferService.java
dpp-backend/digitalproductpass/src/main/resources/application.yml
dpp-backend/digitalproductpass/src/test/java/managers/ProcessManagerTest.java
dpp-backend/digitalproductpass/src/test/java/utils/PolicyUtilTest.java
dpp-backend/digitalproductpass/src/test/resources/application-test.yml
dpp-frontend/src/utils/edcUtil.js

Fixed edc policy breaking changes in the backend to be compatible with the edc `v0.7.3`
The must be compatible with the edc `v0.7.3` 
- Fixed EDC compatibility issues in the backend

Bugfix/edc policy: Fixed breaking changes in the backend

---

.github/workflows/trufflehog.yaml

There is a requirement in [trg-8.03](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-03) to introduce TruffleHog secret scanning tool as an altertive to Gitguardian. Since, Gitguardian is no more used, it should be offboarded and TruffleHog must be used in place.
Replace Gitguardian with TruffleHog tool https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-03/
- Added truffle hog workflow for secret scanning
Closes #414

Hotfix: Add TruffleHog workflow for Secret Scanning

---

DEPENDENCIES_BACKEND
dpp-backend/digitalproductpass/pom.xml

There was a HIGH security vulnberability discovered in spring boot dependency which must be resolved.
- Upgraded spring boot parent version from `3.3.1` to `3.3.3`
https://github.com/eclipse-tractusx/digital-product-pass/security/code-scanning/1978

Hotfix: Upgraded springboot parent version
